### ISSUE TITLE
Incompatible with Meteor's DDPGracefulShutdown

### ISSUE THREAD

**Issue by alexnault** [copleykj/socialize-server-presence#3]
Hey, super cool package! We are currently using it in a very large scale Meteor app and it's causing us issues with [Meteor's DDPGracefulShutdown](https://github.com/meteor/ddp-graceful-shutdown).

DDPGracefulShutdown aims to disconnect users slowly on a SIGTERM to ease deployments.

The problem seems to be coming from the `process.exit()` in the `server` collection observer which kills servers during deployments, cancelling DDPGracefulShutdown.

Would it be possible to terminate the process in a graceful manner?
Or to remove `process.exit()` altogether knowing that the server will write to DB on the next heartbeat anyway?

**Comment by copleykj** [comment]
Yeah, I don't see any reason that `process.exit()` can't be removed completely. Kind of selfish of the package to assume that nothing else will attempt to catch the exit.

**Comment by copleykj** [comment]
Is this the only package in the set that your app uses?

**Comment by alexnault** [comment]
@copleykj Yes, we wrote our own minimalist implementation of `socialize-user-presence`.

**Comment by copleykj** [comment]
Awesome! We've done a lot of updates to the package set and are really close to a release. Since you guys aren't using any other packages in the set that would cause the dependency resolver to hold back the upgrade of the server presence package I can get this fix in and issue a release just for this package.

**Comment by copleykj** [comment]
There you go.

**Comment by alexnault** [comment]
Hmm, `process.exit()` is still called on https://github.com/copleykj/socialize-server-presence/blob/master/server-presence.js#L49. Is it intentional?

I don't see why the sync needs to happen both ways. The servers should keep the DB up-to-date and never the other way around.

Here's how I see it - there are 2 possible scenarios when a `server` document is removed:
1.  Server has already terminated itself.
2. Server is still online but failed to update the `server` document in time (it might be in the middle a deployment). It shouldn't be asked to shutdown. It will update the document when it gets the opportunity.

Or maybe I'm missing something? Thoughts?

**Comment by copleykj** [comment]
So basically what's going on here is the server detects that it's own document has been removed from the database. If the server is the currently the "watcher" it'll just recover by reinserting it's document and things will go on as normal.. If it's not the watcher though, this means that another server is and it has just executed any cleanup functions that were registered. This leaves the application in a state that assumes the server has died and no reliable way to recover from this situation, therefore the last resort is to just exit and come back with a fresh consistent state.

The reason for the `exit()` is that in its current configuration calling `process.kill(process.pid, 'SIGHUP')` would execute the `process.on('SIGHUP')` calling the stop method which would try to update the document that's been deleted from the server and run the cleanup functions that were already run. This is an easy fix though and I'll get fixed and released so you guys can get back to worrying about the big issues :smiley:

**Comment by copleykj** [comment]
Should be all set. Let me know if you need anything else.

**Comment by alexnault** [comment]
You guys are awesome; we'll test it when we get a chance and keep you posted!

**Comment by copleykj** [comment]
Hey @anault, just wanted to make sure the fix was satisfactory.

**Comment by alexnault** [comment]
We are deploying the fix this week and then we'll have to test it against another deployment (probably next week). I'll come back with an answer asap.

**Comment by alexnault** [comment]
It worked! During today's deployment, ongoing connections were gradually moved to new containers as expected. Cheers!
